- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Updating apt
    command : apt update

  - name : Install Docker
    command : apt install docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : Run the Bank application
    command: docker run -dt -p 9000:8081 prafullla/bankingproject
